import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./uxmason.global.css";
import "./uxmason.C.css";
import "./uxmason.T.css";
// TODO: DB 준비 후 주석 해제
// import EventLoggerProvider from "@/components/EventLoggerProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased isHighEnd isMidRange userIsMale`}
      >
        {/* TODO: DB 준비 후 주석 해제 */}
        {/* <EventLoggerProvider>{children}</EventLoggerProvider> */}
        {children}
      </body>
    </html>
  );
}
